# Compose file for a RedtT Validator node

version: "3.7"
services:
  redtval:
    build: ./redtval
    container_name: redtval
    volumes:
      - "./redtval/data_dir:/root/alastria/data"
    ports:
      - "21000:21000/tcp"
      - "21000:21000/udp"
